apiVersion: apps/v1

kind: Deployment
metadata:
  name: deployment-app
  labels:
    app: myapp
    tier: front-end

spec:
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.5-err

  replicas: 3
  selector:
    matchLabels:
      app: myapp
